### PR TITLE
Implemented "ToContainKey" matcher (Issue #62)

### PR DESCRIPTION
**Pull request by m1ome**

### CODE REVIEW

**Comment by jails** [comment]
Awesome :+1: !
If an instance is `Traversable` it means that it has the [following methods implemented](http://php.net/manual/fr/class.iterator.php). So `isset()` will throw an exception since `isset()` works for an `array` or `offsetExists` is implemented through `ArrayAccess`. So you have no other alternative to iterate over it when the instance is only `Traversable`.

However it's perfect, just squash it after that so I can merge it.

**Comment by m1ome** [comment]
@jails ok i will update it with a `Traversable` support and squash a commits, that you can merge it.

**Comment by m1ome** [comment]
@jails, squashed it!

**Comment by m1ome** [comment]
Squash it!

**Comment by jails** [comment]
:+1: !!

**Pull request merged**
