### PR TITLE
Implemented pretty reporter.

### PR DESCRIPTION
**Pull request by m1ome**
Trying to get some pretty and informative reporter peridot-style.

### CODE REVIEW

**Comment by jails** [comment]
That's interesting, maybe the best option would be to merge this reporter to the verbose one. And using the same kind of looks and feels for other reporters to have something "homogenous" and taking the opportunity to share the same codebase for displaying reportings.
The only issue is the black color. Since terminal backgrounds are generaly white or black id we explicitly use a white color or a black color it'll ends up to be problematic for some people. So the terminal default color should be used instead. Imo, the only color we can safely use are the bright colors since is highly improbable people use that kind of color as terminal background.

Also saw the following error when tried to make a spec to fail:
```php
Exception: `kahlan\PhpErrorException` Code(0) with message "`E_NOTICE` Array to string conversion" in /home/jaillet/code/crysalead/kahlan/src/cli/Cli.php:170
        Trace: 
          [NA] - /home/jaillet/code/crysalead/kahlan/src/cli/Cli.php, line  to 170
          kahlan\cli\Cli::color() - /home/jaillet/code/crysalead/kahlan/src/reporter/Terminal.php, line 60
          kahlan\reporter\Terminal::write() - /home/jaillet/code/crysalead/kahlan/src/reporter/Pretty.php, line 84
          kahlan\reporter\Pretty::_report() - /home/jaillet/code/crysalead/kahlan/src/reporter/Pretty.php, line 26
          kahlan\reporter\Pretty::fail() - /home/jaillet/code/crysalead/kahlan/src/Reporters.php, line 86
```

**Comment by m1ome** [comment]
It's kind hard to to this kind of reporter. Kahlan system just report of each one "expect()" it's good, obvious, but have a problem if i try to do some kind of pretty reporter that show me only full "it-should" fail or pass. 

I see a two ways:
1. Make kahlan even more faster and report for "it" only with a sub-array of "expectations" failed/passed/skipped.
2. Do a base code-styled reporter that uses semantic neither of "expecte" reporting in favour of "it-should" reporting.

The first way seems more good for me, it will more easy to make own reporter. Now it's kinda hard to do.
It looks like i am missing some checking

**Comment by jails** [comment]
Maybe we can do both and just add an extra `spec()` entry point which will receive a summary of all runned expectations. It will probably need to do some internal refactoring.

**Comment by m1ome** [comment]
It's no need to do both ways. It's obvious don't need to be so, let me explain. Now system reacts on every "expect()" and send it to reporter, and it can be refactored, and push to reporter only information about `it()` with an extra fields in it, something like:

```php
[
  "spec"    => "SomeMySpec",
  "file"    => "/path/to/my/spec/Spec.php",
  "message" => "it should check something",
  "type"    => "fail",
  "info"    => [
    [
      "line"    => 127,
      "type"    => "pass"
    ],
    [
      "line"      => 130,
      "type"      => "fail",
      "expected"  => [...],
      "actual"    => [...]
    ]
  ]
]
```

**Comment by jails** [comment]
The main processing time is spend to build report summaries. Since `pass()`, `fail()`, etc. are simple calls, they are imo negligible. And moreover they allow the Dot reporter to spit out dots/fails as they occur instead of having a bunch of them to be spitted out in one go.
So imo the best option is to pass a complete report to https://github.com/crysalead/kahlan/blob/master/src/reporter/Reporter.php#L66 which the result of all expectations exectuted in the spec.

**Comment by m1ome** [comment]
We talking about different things. I am asking to have a reporter, that will catch every `it` occurrence and check if it passed or failed. With a additional data it will be able to do a Dot reporter also, just need to traverse a `info` array, but points will be showing with a small chunks.

**Comment by jails** [comment]
This callback https://github.com/crysalead/kahlan/blob/master/src/reporter/Reporter.php#L66 is definitly called after each `it` occurrence. So it only need to receive the report of all exectuted expectations to be able to create a reporter you are talking about imo.

**Comment by m1ome** [comment]
In that way - yes.

**Comment by m1ome** [comment]
Could you please fetch this one? 
After refactoring in reporters we can merge this reporter with a verbose one.
IMO refactoring can cause a BC break.

**Comment by jails** [comment]
I think I will need some more time to refactor correctly the reporting layer.

**Comment by m1ome** [comment]
You think you can do it without BC break?

**Comment by jails** [comment]
Well BC break doesn't really matter for reporting.
In the last dev, reports are now instances instead of arrays and I think it'll be easier to deal with.
And the `after()` callback now receive the report of the whole spec. Which means `->childs()` will returns an array of reports of all exectuted `expect()` inside the spec.

**Comment by m1ome** [comment]
:+1:

**Comment by m1ome** [comment]
I can rebase and adopt reporter to a new logic?

**Comment by jails** [comment]
Yup it should work as expected, but maybe there's still some refactoring glitches since I didn't test deeply this refactoring. Anyway specs are passing.

**Comment by m1ome** [comment]
Ok, i'll try to rebase and work on it

**Pull request closed without merging**
