### PR TITLE
Monkey Patching fix (related to #64)

### PR DESCRIPTION
**Pull request by m1ome**

### CODE REVIEW

**Comment by jails** [comment]
Thanks for the head up man :+1: 
Fixed in https://github.com/crysalead/kahlan/commit/9a25da5947e3ca469b008e44b09fb7e872ee715e

**Comment by m1ome** [comment]
When @jails don't wanna your **PR**
Sadness

**Comment by jails** [comment]
Haha it's just beause the PR misses `xor`. But the fact you nailed the issue saved me some time.

**Comment by m1ome** [comment]
Just kidding :smile:

**Pull request closed without merging**
