### PR TITLE
Improvements in code-coverage.

### PR DESCRIPTION
**Pull request by m1ome**
Basic improvements in code coverage.
Fixed possible bug in d784c70 with Debugger config.

### CODE REVIEW

**Comment by jails** [comment]
If you follow the Travis CI details link you should see that one test is failing. Does it pass for you locally ?

**Comment by m1ome** [comment]
Fixed this issue

**Comment by m1ome** [comment]
Yeah, it passed locally, but it's about a Stub dummy creation something like "Stub<NN>" and locally it always created "Stub0" and in travis number was another, my bad.

**Comment by jails** [comment]
Just for your information I just added some minor fixes on top of your work (https://github.com/crysalead/kahlan/commit/bd748d41275f35560c29c6eb86ec222bfa9a1d37)
- fixes some minor typo
- fixes `DummyClass` patcher core specs instead according to your spec
- removed `spec/suite/reporter/VerboseSpec.php` since there was no spec in
- removed `Debugger::config()` method since it has been deprecated

**Comment by m1ome** [comment]
You are welcome

**Pull request merged**
