### PR TITLE
Code coverage improvements. Some minor fixes.

### PR DESCRIPTION
**Pull request by m1ome**
Improvements in code coverage;
I found a function into `kahlan\analysis\Debugger.php`:

        // This code will never fire, because of backtrace closure checking
        // Please check this!
        // if (strpos($trace['function'], '{closure}') !== false) {
        //     $trace['function'] = "{closure}";
        // }

I commented it, though it will never fire based on Debugger backtrace method logic.

### CODE REVIEW

**Comment by m1ome** [comment]
I think you should merge it manually, we have some difference on development branch.

**Comment by m1ome** [comment]
Coverage now is "97.57". And all matchers full code covered.

**Comment by jails** [comment]
Imo you should be able to make it work using the following command:
Adding this repo as upstream (if not done):
```
git remote add upstream git@github.com:crysalead/kahlan.git
```
Then rebasing your w1n2k commits on top of the dev branch
```
git fetch upstream
git rebase upstream/dev
git push origin w1n2k -f
```
Makes sense ?

**Comment by m1ome** [comment]
I merged it.
It's not a good idea to rebase on a already pushed to remote.

**Comment by jails** [comment]
As long as a PR is not merged it would have been the way to go.
Because right now the PR is really messy and doesn't reflect the changes.
Will try to untangle it.

**Comment by m1ome** [comment]
Maybe i am not so good at this point. It looking messy right now, yes.

**Pull request closed without merging**
