### PR TITLE
Small typo fixes

### PR DESCRIPTION
**Pull request by i-am-tom**
Hello,

Firstly, this software is awesome - I'm a total convert! This PR unfortunately doesn't contribute much; just a couple of typos I noticed in the CLI. The spec has also been updated to match :)

### CODE REVIEW

**Comment by m1ome** [comment]
@i-am-tom can you squash commits to one?

**Comment by i-am-tom** [comment]
Hah, hadn't noticed the merge commit! Should be squashed.

**Comment by m1ome** [comment]
@jails if you ok about this one i'll merge it.

**Comment by jails** [comment]
Thanks for the PR @i-am-tom and glad you like Kahlan ! Using the `describe`/`it` DSL is probably the paradigm which saved my time the most during tests maintenance.
@m1ome, it's fine for me you can merge on dev :+1:

**Pull request merged**
