### PR TITLE
Coverage improvements

### PR DESCRIPTION
**Pull request by m1ome**

### CODE REVIEW

**Comment by jails** [comment]
:+1: 
Squashed & merged https://github.com/crysalead/kahlan/commit/84f1c522a56dff24d7b259ac0edf5c53e25a7b3c

**Comment by m1ome** [comment]
Forgot about `Stub::classname` :+1:

**Comment by m1ome** [comment]
Chuck Kahlan is 99.7% tested. I think a 100% code coverage will have Chuck seal of approve.

**Comment by jails** [comment]
Haha yeah definitly, good job :+1: !!

**Pull request closed without merging**
