### PR TITLE
Improvements in code coverage.

### PR DESCRIPTION
**Pull request by m1ome**
Improved code coverage in:

```
jit\patcher\DummyClass
plugin\Quit
plugin\call\Message
reporter/coverage/exporter/Clover
reporter/coverage/exporter/Coveralls
reporter/coverage/exporter/CodeClimat
```

### CODE REVIEW

**Comment by m1ome** [comment]
Travis reporting:

```
PHP Fatal error:  Call to undefined method kahlan\plugin\call\Message::getName()
```

It is strange, because in my `dev` branch getName method exists in Message.

**Comment by jails** [comment]
You probably worked on a outdatted dev.

```
git fetch upstream
git rebase upstream/dev
git push origin m1ome-dev -f
```

**Comment by jails** [comment]
I cherry picked the commit & added the clean commit https://github.com/crysalead/kahlan/commit/93d63e728e82cafc8fd9c4109ec401b8aca5c02b

**Comment by m1ome** [comment]
Strange, i checked that i work on last changeset. Thanks!

**Pull request closed without merging**
