### PR TITLE
Pretty reporter implementation

### PR DESCRIPTION
**Pull request by m1ome**

### CODE REVIEW

**Comment by m1ome** [comment]
It's seems like you broke something in Exception reporting.
Please check it, for me it's more complicated, that for you :smiley:

**Comment by jails** [comment]
I think I'm almost done, only need to harmonize all reporters to obtain the same kind of look and feel and I will probably merge both pretty & verbose which deserve almost the same goal.

**Comment by jails** [comment]
All reporters have now the same look & feel https://github.com/crysalead/kahlan/commit/df90682214fce7e3f16e8129441275a6b898c9f2

**Comment by m1ome** [comment]
:+1: nice work!

**Pull request merged**
