### PR TITLE
Added release version inside of composer.json

### PR DESCRIPTION
**Pull request by m1ome**

### CODE REVIEW

**Comment by jails** [comment]
Maybe `"crysalead/kahlan": "~1.0"` would be more appropriate since a bump up of a minor number can introduce some BC break.

**Comment by m1ome** [comment]
It only a matter what will you do with Minor.

On my mind the best way to split something like this: **Major**.**Minor**.**Patch**.

**Major** - something that break backwards API capability.
**Minor** - something that improves/add current functionality but not breaks backwards API capability.
**Patch** - something that fix a bug and not break backwards API capability.

It's only your choice, i can only suggest :8ball:

**Comment by jails** [comment]
I think it'll be probably better here to follow some generic meaning like [semver](http://semver.org/) so people can rely on some generic "meaning" when they are buildling their `composer.json`.

**Comment by m1ome** [comment]
I quoted semver meaning of MAJOR.MINOR.PATCH :smile:

**Comment by jails** [comment]
Ah yeah indeed, get confused by [this recent reading](http://www.jongleberry.com/semver-has-failed-us.html).

**Comment by m1ome** [comment]
It's good article. You can use a [ferver](https://github.com/jonathanong/ferver) instead. It is more flexible, but release will look like 1.10.100500 :smiley:

**Comment by jails** [comment]
After reading a couple of intense debate over semver, my conclusion is the initial "pain-free" promise seems to be wrong. And after looking over Kahlan's commit looks like one each other patch can be considered as BC-break in a sense that people may use the behavior in the "buggy" way. So yeah [ferver](https://github.com/jonathanong/ferver) makes a lot more sense. I think I'll continue to move that way and adding this reference in this readme.

**Comment by jails** [comment]
Note about ferver versioning added in https://github.com/crysalead/kahlan/commit/43a872f38ab4b2fd429fc2280fef9550e8b7d9ec !

**Comment by m1ome** [comment]
:+1:

**Pull request closed without merging**
